# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "KEmoji"
SPDX-PackageSupplier = "James Graham <james.h.graham@protonmail.com>"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["data/*.dict"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Unicode Consortium"
SPDX-License-Identifier = "Unicode-3.0"

[[annotations]]
path = "autotests/data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
